import { useEffect, useState } from 'react';
import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Button, Card, Chip, Field, PageHeader, Screen } from '@/components/ui';
import { InvestmentQuiz, InvestmentResult } from '@/components/InvestmentQuiz';
import { colors } from '@/constants/theme';
import { get, post } from '@/lib/api';
import { useAuth } from '@/context/AuthContext';

export default function Register(){
 const {acceptAuth}=useAuth();const [step,setStep]=useState<'form'|'quiz'>('form'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[usernameCheck,setUsernameCheck]=useState<any>({value:'',checking:false,available:null,message:''});
 const [form,setForm]=useState({username:'',password:'',password_confirm:'',display_name:'',gender:'prefer_not_to_say',birth_date:'',phone_number:'',age_14_or_older:false,terms_consent:false,privacy_consent:false});
 const u=(k:string,v:any)=>setForm(f=>({...f,[k]:v}));
 useEffect(()=>{const value=form.username.trim();setUsernameCheck((x:any)=>x.value===value?x:{value,checking:false,available:null,message:''});if(!/^[A-Za-z0-9._-]{3,60}$/.test(value))return;let live=true;const t=setTimeout(async()=>{setUsernameCheck({value,checking:true,available:null,message:'확인 중...'});try{const r=await get<any>('/api/auth/check-username',{username:value},false);if(live)setUsernameCheck({value,checking:false,available:!!r.available,message:r.message||''})}catch(e:any){if(live)setUsernameCheck({value,checking:false,available:null,message:e.message||'아이디 확인 실패'})}},280);return()=>{live=false;clearTimeout(t)}},[form.username]);
 const next=()=>{setError('');const value=form.username.trim();if(!/^[A-Za-z0-9._-]{3,60}$/.test(value)){setError('아이디는 영문, 숫자, ., _, - 조합으로 3자 이상 입력해주세요.');return}if(usernameCheck.value!==value||usernameCheck.available!==true){setError('아이디 사용 가능 여부를 확인해주세요.');return}if(form.password.length<8){setError('비밀번호는 8자 이상 입력해주세요.');return}if(form.password!==form.password_confirm){setError('비밀번호 확인이 일치하지 않습니다.');return}if(form.display_name.trim().length<2){setError('이름을 2자 이상 입력해주세요.');return}if(!/^\d{4}-\d{2}-\d{2}$/.test(form.birth_date)){setError('생년월일은 YYYY-MM-DD 형식으로 입력해주세요.');return}const born=new Date(`${form.birth_date}T00:00:00`);if(Number.isNaN(born.getTime())){setError('생년월일을 확인해주세요.');return}const today=new Date(),age=today.getFullYear()-born.getFullYear()-((today.getMonth()<born.getMonth()||(today.getMonth()===born.getMonth()&&today.getDate()<born.getDate()))?1:0);if(age<14||age>120||!form.age_14_or_older){setError('만 14세 이상 확인이 필요합니다.');return}if(form.phone_number.replace(/\D/g,'').length<10){setError('휴대폰 번호를 정확히 입력해주세요.');return}if(!form.terms_consent||!form.privacy_consent){setError('필수 약관과 개인정보 수집·이용에 동의해주세요.');return}setStep('quiz')};
 const complete=async(result:InvestmentResult)=>{setBusy(true);setError('');try{const {password_confirm,age_14_or_older,...payloadForm}=form;const payload=await post<any>('/api/auth/register',{...payloadForm,username:form.username.trim(),display_name:form.display_name.trim(),investment_profile:{result_code:result.code,answers:result.serializedAnswers,scores:{counts:result.counts,percentages:result.percentages}}},false);await acceptAuth(payload);router.replace('/(tabs)')}catch(e:any){setError(e.message||'회원가입에 실패했습니다.')}finally{setBusy(false)}};
 return <Screen>{step==='form'?<><PageHeader eyebrow="JOIN STOCKLOG" title="회원가입" subtitle="웹과 동일하게 아이디 중복 확인·필수 정보 입력 후 30문항 투자성향 검사를 진행합니다."/><Card style={{gap:12}}><Field label="아이디" value={form.username} onChangeText={v=>u('username',v)} autoCapitalize="none" placeholder="영문/숫자/._- 3자 이상"/><View style={styles.checkLine}><Chip label={usernameCheck.checking?'확인 중':usernameCheck.available===true?'사용 가능':usernameCheck.available===false?'사용 불가':'중복 확인'} active={usernameCheck.available===true}/><Text style={[styles.checkMessage,usernameCheck.available===false&&{color:colors.danger}]}>{usernameCheck.message}</Text></View><Field label="비밀번호" value={form.password} onChangeText={v=>u('password',v)} secureTextEntry placeholder="8자 이상"/><Field label="비밀번호 확인" value={form.password_confirm} onChangeText={v=>u('password_confirm',v)} secureTextEntry placeholder="동일하게 한 번 더 입력"/><Field label="이름" value={form.display_name} onChangeText={v=>u('display_name',v)} placeholder="이름"/><Text style={styles.label}>성별</Text><View style={styles.chips}>{[['male','남성'],['female','여성'],['other','기타'],['prefer_not_to_say','응답 안 함']].map(([v,l])=><Pressable key={v} onPress={()=>u('gender',v)} style={[styles.choice,form.gender===v&&styles.choiceOn]}><Text style={[styles.choiceText,form.gender===v&&{color:colors.primary}]}>{l}</Text></Pressable>)}</View><Field label="생년월일" value={form.birth_date} onChangeText={v=>u('birth_date',v)} placeholder="2000-01-01" keyboardType="numbers-and-punctuation"/><Field label="휴대폰 번호" value={form.phone_number} onChangeText={v=>u('phone_number',v)} placeholder="01012345678" keyboardType="phone-pad"/>{[['age_14_or_older','만 14세 이상입니다.'],['terms_consent','이용약관에 동의합니다.'],['privacy_consent','개인정보 수집·이용에 동의합니다.']].map(([k,l])=><Pressable key={k} onPress={()=>u(k,!form[k as keyof typeof form])} style={styles.check}><View style={[styles.box,form[k as keyof typeof form]&&styles.boxOn]}><Text style={{color:'#fff',fontWeight:'900'}}>{form[k as keyof typeof form]?'✓':''}</Text></View><Text style={styles.checkText}>{l}</Text></Pressable>)}{error?<Text style={styles.error}>{error}</Text>:null}<Button title="투자성향 검사 시작" onPress={next}/><Button title="로그인으로 돌아가기" tone="ghost" onPress={()=>router.back()}/></Card></>:<><PageHeader eyebrow="INVESTOR DNA" title="투자성향 검사" subtitle="30문항을 모두 선택하면 가입이 완료됩니다." right={<Button compact tone="ghost" title="정보 수정" onPress={()=>setStep('form')}/>}/>{error?<Text style={styles.error}>{error}</Text>:null}<InvestmentQuiz onComplete={complete} submitting={busy}/></>}</Screen>;
}
const styles=StyleSheet.create({label:{fontSize:12,fontWeight:'700',color:colors.text2},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},choice:{paddingHorizontal:11,paddingVertical:9,borderRadius:999,borderWidth:1,borderColor:colors.border},choiceOn:{borderColor:colors.primary,backgroundColor:colors.primarySoft},choiceText:{fontSize:11,fontWeight:'700',color:colors.text2},check:{flexDirection:'row',alignItems:'center',gap:9,paddingVertical:4},box:{width:22,height:22,borderRadius:7,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},boxOn:{backgroundColor:colors.primary,borderColor:colors.primary},checkText:{fontSize:12,color:colors.text2},error:{fontSize:12,color:colors.danger,lineHeight:18},checkLine:{flexDirection:'row',gap:8,alignItems:'center',flexWrap:'wrap'},checkMessage:{fontSize:10,color:colors.text3,flex:1}});
