import { useEffect, useState } from 'react';
import { router } from 'expo-router';
import * as SecureStore from 'expo-secure-store';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Button, Card, Field, PageHeader, Screen } from '@/components/ui';
import { InvestmentQuiz, InvestmentResult } from '@/components/InvestmentQuiz';
import { colors } from '@/constants/theme';
import { post } from '@/lib/api';
import { useAuth } from '@/context/AuthContext';

const PENDING='stocklog_pending_social_v1';
export default function SocialComplete(){
 const {acceptAuth}=useAuth(); const [pending,setPending]=useState<any>(null); const [step,setStep]=useState<'info'|'quiz'>('info'); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
 const [form,setForm]=useState({name:'',gender:'prefer_not_to_say',birth_year:'',phone_number:'',age_14_or_older:true,terms_consent:false,privacy_consent:false});
 useEffect(()=>{SecureStore.getItemAsync(PENDING).then(raw=>{if(!raw){router.replace('/login');return}try{const p=JSON.parse(raw);setPending(p);setForm(f=>({...f,name:p.display_name||'',gender:p.gender||'prefer_not_to_say',birth_year:p.birth_year?String(p.birth_year):'',phone_number:p.phone_number||''}))}catch{router.replace('/login')}})},[]);
 const locked=new Set(pending?.locked_fields||[]); const u=(k:string,v:any)=>setForm(f=>({...f,[k]:v}));
 const next=()=>{if(form.name.trim().length<2||!/^\d{4}$/.test(form.birth_year)||form.phone_number.replace(/\D/g,'').length<10||!form.terms_consent||!form.privacy_consent||!form.age_14_or_older){setError('회원 정보와 필수 동의를 모두 확인해주세요.');return}setError('');setStep('quiz')};
 const complete=async(result:InvestmentResult)=>{setBusy(true);setError('');try{const payload=await post<any>('/api/auth/social/complete',{session_id:pending.session_id,signup_info:{...form,birth_year:Number(form.birth_year)},investment_profile:{result_code:result.code,answers:result.serializedAnswers,scores:{counts:result.counts,percentages:result.percentages}}},false);await SecureStore.deleteItemAsync(PENDING);await acceptAuth(payload);router.replace('/(tabs)')}catch(e:any){setError(e.message||'소셜 회원가입을 완료하지 못했습니다.')}finally{setBusy(false)}};
 if(!pending)return <Screen><Text style={{color:colors.text3}}>소셜 로그인 정보를 확인 중...</Text></Screen>;
 return <Screen>{step==='info'?<><PageHeader eyebrow="SOCIAL SIGN UP" title={`${pending.provider_label||'소셜'} 회원가입`} subtitle="처음 로그인한 소셜 계정입니다. 필요한 회원정보를 확인해주세요."/><Card style={{gap:12}}><Field label="이름" value={form.name} editable={!locked.has('name')} onChangeText={v=>u('name',v)} /><Text style={styles.label}>성별</Text><View style={styles.chips}>{[['male','남성'],['female','여성'],['other','기타'],['prefer_not_to_say','응답 안 함']].map(([v,l])=><Pressable key={v} disabled={locked.has('gender')} onPress={()=>u('gender',v)} style={[styles.choice,form.gender===v&&styles.choiceOn]}><Text style={styles.choiceText}>{l}</Text></Pressable>)}</View><Field label="출생연도" value={form.birth_year} editable={!locked.has('birth_year')} onChangeText={v=>u('birth_year',v)} keyboardType="number-pad"/><Field label="휴대폰" value={form.phone_number} editable={!locked.has('phone_number')} onChangeText={v=>u('phone_number',v)} keyboardType="phone-pad"/>{[['age_14_or_older','만 14세 이상입니다.'],['terms_consent','이용약관에 동의합니다.'],['privacy_consent','개인정보 수집·이용에 동의합니다.']].map(([k,l])=><Pressable key={k} onPress={()=>u(k,!form[k as keyof typeof form])} style={styles.check}><View style={[styles.box,form[k as keyof typeof form]&&styles.boxOn]}><Text style={{color:'#fff',fontWeight:'900'}}>{form[k as keyof typeof form]?'✓':''}</Text></View><Text style={styles.checkText}>{l}</Text></Pressable>)}{error?<Text style={styles.error}>{error}</Text>:null}<Button title="투자성향 검사 시작" onPress={next}/></Card></>:<><PageHeader eyebrow="INVESTOR DNA" title="투자성향 검사" subtitle="30문항 완료 후 소셜 계정 생성이 끝납니다."/>{error?<Text style={styles.error}>{error}</Text>:null}<InvestmentQuiz onComplete={complete} submitting={busy}/></>}</Screen>
}
const styles=StyleSheet.create({label:{fontSize:12,fontWeight:'700',color:colors.text2},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},choice:{paddingHorizontal:11,paddingVertical:9,borderRadius:999,borderWidth:1,borderColor:colors.border},choiceOn:{borderColor:colors.primary,backgroundColor:colors.primarySoft},choiceText:{fontSize:11,fontWeight:'700',color:colors.text2},check:{flexDirection:'row',alignItems:'center',gap:9,paddingVertical:4},box:{width:22,height:22,borderRadius:7,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center'},boxOn:{backgroundColor:colors.primary,borderColor:colors.primary},checkText:{fontSize:12,color:colors.text2},error:{fontSize:12,color:colors.danger}});
