import { useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Button, Card, Chip, ErrorState, Field, Loading, PageHeader, Screen, SectionTitle, Stat } from '@/components/ui';
import { colors } from '@/constants/theme';
import { del, get, post, put } from '@/lib/api';
import { errorText } from '@/lib/format';
const defs:any={naver:{label:'네이버 뉴스',kind:'naver'},dart:{label:'OpenDART',kind:'key'},gemini:{label:'StockLog Gbot',kind:'key'}};
export default function ExternalApis(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[forms,setForms]=useState<any>({naver:{},dart:{},gemini:{}}),[busy,setBusy]=useState('');
 const load=async()=>{try{setData(await get('/api/admin/external-apis'));setError('')}catch(e){setError(errorText(e))}};useEffect(()=>{void load()},[]);
 const update=(p:string,k:string,v:any)=>setForms((x:any)=>({...x,[p]:{...(x[p]||{}),[k]:v}}));
 const save=async(p:string)=>{setBusy(`save-${p}`);try{const f=forms[p]||{},old=data[p]||{};const payload=p==='naver'?{client_id:f.client_id||'',client_secret:f.client_secret||'',enabled:f.enabled??old.enabled??true}:{api_key:f.api_key||'',enabled:f.enabled??old.enabled??true};await put(`/api/admin/external-apis/${p}`,payload);setForms((x:any)=>({...x,[p]:{}}));await load();Alert.alert('저장 완료',`${defs[p].label} 설정을 저장했습니다.`)}catch(e){Alert.alert('저장 실패',errorText(e))}finally{setBusy('')}};
 const test=async(p:string)=>{setBusy(`test-${p}`);try{const r=await post<any>(`/api/admin/external-apis/${p}/test`,{});Alert.alert('연결 테스트',r?.message||'정상입니다.');await load()}catch(e){Alert.alert('테스트 실패',errorText(e));await load().catch(()=>{})}finally{setBusy('')}};
 const remove=(p:string)=>Alert.alert('API 설정 삭제',`${defs[p].label}의 MySQL 저장 설정을 삭제할까요? .env 설정이 있으면 fallback으로 사용됩니다.`,[{text:'취소'},{text:'삭제',style:'destructive',onPress:async()=>{setBusy(`delete-${p}`);try{const r=await del<any>(`/api/admin/external-apis/${p}`);Alert.alert('삭제 완료',r?.message||'삭제했습니다.');await load()}catch(e){Alert.alert('삭제 실패',errorText(e))}finally{setBusy('')}}}]);
 return <Screen><PageHeader eyebrow="ADMIN" title="외부 API / AI" subtitle="뉴스·공시·Gbot 연결 상태와 StockLog 기록 사용량을 관리합니다." right={<Button compact tone="ghost" title="닫기" onPress={()=>router.back()}/>}/>{error?<ErrorState message={error} retry={()=>void load()}/>:!data?<Loading/>:Object.keys(defs).map(p=>{const d=data[p]||{},f=forms[p]||{},usage=d.usage||{},enabled=f.enabled??d.enabled??true;return <Card key={p}><SectionTitle title={defs[p].label} right={<Chip label={d.configured?'연동':'미연동'} active={!!d.configured}/>}/><Text style={s.status}>연결 {d.configured?'설정됨':'미설정'} · 저장 키 {d.api_key_masked||d.client_id_masked||'미설정'}</Text><Text style={s.label}>사용 여부</Text><View style={s.actions}><Chip label="사용" active={enabled===true} onPress={()=>update(p,'enabled',true)}/><Chip label="비활성" active={enabled===false} onPress={()=>update(p,'enabled',false)}/></View>{p==='naver'?<><Field label="Client ID" value={f.client_id||''} onChangeText={v=>update(p,'client_id',v)} placeholder={d.client_id_masked||'비우면 기존 값 유지'}/><Field label="Client Secret" secureTextEntry value={f.client_secret||''} onChangeText={v=>update(p,'client_secret',v)} placeholder={d.configured?'변경 시에만 입력':'Client Secret'}/></>:<Field label={p==='gemini'?'Gbot API Key':'API Key'} secureTextEntry value={f.api_key||''} onChangeText={v=>update(p,'api_key',v)} placeholder={d.api_key_masked||'비우면 기존 값 유지'}/>}<View style={s.actions}><Button compact title={busy===`save-${p}`?'저장 중':'저장'} disabled={!!busy} onPress={()=>void save(p)}/><Button compact tone="secondary" title="연결 확인" disabled={!!busy||!d.configured} onPress={()=>void test(p)}/>{d.stored_in_mysql?<Button compact tone="danger" title="삭제" disabled={!!busy} onPress={()=>remove(p)}/>:null}</View>{Object.keys(usage).length?<Card style={s.usageCard}><Text style={s.label}>오늘 사용량</Text><View style={s.metrics}><Stat label="총 호출" value={Number(usage.total_calls||0).toLocaleString()}/><Stat label="성공" value={Number(usage.successful_calls||0).toLocaleString()}/><Stat label="실패" value={Number(usage.failed_calls||0).toLocaleString()}/></View>{usage.daily_limit!=null?<Text style={s.usage}>한도 {Number(usage.daily_limit).toLocaleString()} · 사용률 {Number(usage.usage_percent||0).toFixed(1)}% · 최근 1시간 {Number(usage.recent_hour_calls||0).toLocaleString()}</Text>:null}{p==='gemini'?<Text style={s.usage}>남은 안전 한도 {Number(usage.remaining_calls??usage.daily_limit??0).toLocaleString()} · 백그라운드 {Number(usage.background_calls||0).toLocaleString()}회</Text>:null}</Card>:null}</Card>})}</Screen>;
}
const s=StyleSheet.create({status:{fontSize:11,color:colors.text3,marginBottom:10},label:{fontSize:10,fontWeight:'800',color:colors.text3,marginBottom:6},actions:{flexDirection:'row',gap:8,marginTop:8,flexWrap:'wrap'},usage:{fontSize:10,lineHeight:15,color:colors.text3,marginTop:8},usageCard:{marginTop:12,shadowOpacity:0,backgroundColor:colors.surfaceMuted},metrics:{flexDirection:'row',gap:10}});
