import { useCallback, useEffect, useState } from 'react';
import { Alert, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Button, Card, ErrorState, Loading, PageHeader, RowLink, SectionTitle, Stat } from '@/components/ui';
import { colors } from '@/constants/theme';
import { get, post } from '@/lib/api';
import { dateTime, errorText } from '@/lib/format';
export default function AdminHome(){const [status,setStatus]=useState<any>(null),[overview,setOverview]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[refreshing,setRefreshing]=useState(false);const load=useCallback(async()=>{try{const [a,b]=await Promise.all([get('/api/admin/status'),get('/api/admin/sync-overview').catch(()=>null)]);setStatus(a);setOverview(b);setError('')}catch(e){setError(errorText(e))}},[]);useEffect(()=>{void load()},[load]);const run=async(path:string,label:string)=>{setBusy(true);try{const r=await post(path,{});Alert.alert(label,r?.message||'요청을 시작했습니다.');await load()}catch(e){Alert.alert(label,errorText(e))}finally{setBusy(false)}};return <ScrollView style={s.safe} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={async()=>{setRefreshing(true);await load();setRefreshing(false)}}/>}><PageHeader eyebrow="ADMIN" title="운영 현황" subtitle="StockLog 서버와 데이터 동기화 상태" right={<Button compact tone="ghost" title="닫기" onPress={()=>router.back()}/>}/>{error?<ErrorState message={error} retry={()=>void load()}/>:!status?<Loading/>:<><Card><SectionTitle title="핵심 현황"/><View style={s.stats}><Stat label="회원" value={`${status.users||0}명`}/><Stat label="분석 종목" value={`${status.stocks||0}개`}/><Stat label="테마" value={`${status.themes||0}개`}/><Stat label="분류율" value={`${status.classification_coverage_percent||0}%`}/></View><Text style={s.note}>마지막 종목 갱신 {dateTime(status.last_success_at)}</Text>{status.last_error?<Text style={s.err}>{status.last_error}</Text>:null}</Card><Card><SectionTitle title="동기화 제어" hint="대량 작업은 서버에서 실행됩니다."/><View style={s.buttons}><Button title="종목 점수 재계산" tone="secondary" disabled={busy} onPress={()=>run('/api/admin/sync/stocks','종목 동기화')}/><Button title="통합 동기화 시작" disabled={busy} onPress={()=>run('/api/admin/unified-sync/start','통합 동기화')}/><Button title="통합 동기화 중지" tone="danger" disabled={busy} onPress={()=>run('/api/admin/unified-sync/stop','통합 동기화')}/></View></Card>{overview?<Card><SectionTitle title="동기화 모니터" hint={overview.degraded?'캐시된 모니터 상태입니다.':'실시간 모니터 저장소 응답'}/><Text style={s.json}>{summaryOverview(overview)}</Text></Card>:null}<Card><RowLink title="회원 관리" onPress={()=>router.push('/admin/users')}/><RowLink title="외부 API 관리" onPress={()=>router.push('/admin/external')}/><RowLink title="소셜 로그인 설정" onPress={()=>router.push('/admin/social')}/><RowLink title="회원 권한 정책" onPress={()=>router.push('/admin/policies')}/><RowLink title="자동 동기화 설정" onPress={()=>router.push('/admin/schedule')}/><RowLink title="개별 동기화 제어" subtitle="키움·DART·테마·분류·수급 시작/중지" onPress={()=>router.push('/admin/sync-tools')}/><RowLink title="테마 유지보수" subtitle="DB 복구·표준화·커버리지·종목 진단" onPress={()=>router.push('/admin/theme-tools')}/><RowLink title="동기화 진단 로그" subtitle="TXT 로그 조회 및 공유" onPress={()=>router.push('/admin/diagnostics')}/></Card></>}</ScrollView>}
function summaryOverview(x:any){const pick:any={server_time:x.server_time,degraded:x.degraded,unified_sync:x.unified_sync,flow_sync:x.flow_sync,kiwoom_runtime:x.kiwoom_runtime,db_pool:x.db_pool};return JSON.stringify(pick,null,2).slice(0,4500)}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},content:{padding:16,paddingTop:10,paddingBottom:40,gap:14},stats:{flexDirection:'row',flexWrap:'wrap',gap:14},note:{fontSize:11,color:colors.text3,marginTop:12},err:{fontSize:11,color:colors.danger,marginTop:8},buttons:{gap:9},json:{fontFamily:'monospace',fontSize:10,lineHeight:15,color:colors.text2}})
