import { useEffect, useState } from 'react';
import { Alert, StyleSheet, Switch, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Button, Card, Chip, ErrorState, Field, Loading, PageHeader, Screen, SectionTitle } from '@/components/ui';
import { colors } from '@/constants/theme';
import { get, put } from '@/lib/api';
import { dateTime, errorText } from '@/lib/format';
const scopeDefs=[['kiwoom','키움 시세'],['dart','DART 재무'],['kiwoom_themes','키움 테마'],['market_themes','시장 테마'],['classification','분류'],['theme_engine','테마 엔진'],['flow','수급'],['smart_scores','스마트 점수']];
export default function SyncSchedule(){const [form,setForm]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const load=async()=>{try{setForm(await get('/api/admin/unified-sync/schedule'));setError('')}catch(e){setError(errorText(e))}};useEffect(()=>{void load()},[]);const save=async()=>{setBusy(true);try{const r=await put('/api/admin/unified-sync/schedule',{enabled:!!form.enabled,run_times:String((form.run_times||[]).join(',')).split(',').map((x:string)=>x.trim()).filter(Boolean),flow_universe_limit:Number(form.flow_universe_limit||0),flow_history_days:Number(form.flow_history_days||20),scopes:form.scopes||[]});setForm(r.schedule||form);Alert.alert('저장 완료',r.message||'자동 동기화 일정을 저장했습니다.')}catch(e){Alert.alert('저장 실패',errorText(e))}finally{setBusy(false)}};const toggleScope=(k:string)=>setForm((p:any)=>({...p,scopes:(p.scopes||[]).includes(k)?p.scopes.filter((x:string)=>x!==k):[...(p.scopes||[]),k]}));return <Screen><PageHeader eyebrow="ADMIN" title="자동 동기화" subtitle="서버가 정해진 시간에 데이터 전체 동기화를 실행합니다." right={<Button compact tone="ghost" title="닫기" onPress={()=>router.back()}/>}/>{error?<ErrorState message={error} retry={()=>void load()}/>:!form?<Loading/>:<><Card><SectionTitle title="스케줄" hint={`다음 실행 ${dateTime(form.next_run_at)}`}/><View style={s.switchRow}><Text style={s.title}>자동 동기화 사용</Text><Switch value={!!form.enabled} onValueChange={v=>setForm({...form,enabled:v})}/></View><Field label="실행 시각" hint="쉼표로 여러 개 입력: 08:30, 22:00" value={(form.run_times||[]).join(', ')} onChangeText={v=>setForm({...form,run_times:v.split(',').map((x:string)=>x.trim())})}/><View style={s.two}><View style={{flex:1}}><Field label="수급 대상(0=전체)" keyboardType="number-pad" value={String(form.flow_universe_limit||0)} onChangeText={v=>setForm({...form,flow_universe_limit:v})}/></View><View style={{flex:1}}><Field label="수급 기간(일)" keyboardType="number-pad" value={String(form.flow_history_days||20)} onChangeText={v=>setForm({...form,flow_history_days:v})}/></View></View></Card><Card><SectionTitle title="동기화 범위"/><View style={s.chips}>{scopeDefs.map(([k,l])=><Chip key={k} label={l} active={(form.scopes||[]).includes(k)} onPress={()=>toggleScope(k)}/>)}</View><Button title="자동 동기화 저장" disabled={busy||!(form.scopes||[]).length} onPress={save}/></Card></>}</Screen>}
const s=StyleSheet.create({switchRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:12},title:{fontSize:13,fontWeight:'800',color:colors.text},two:{flexDirection:'row',gap:10,marginTop:10},chips:{flexDirection:'row',gap:7,flexWrap:'wrap',marginBottom:14}})
