import { useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import * as WebBrowser from 'expo-web-browser';
import { router } from 'expo-router';
import { Button, Card, Chip, ErrorState, Field, Loading, PageHeader, Screen, SectionTitle } from '@/components/ui';
import { colors } from '@/constants/theme';
import { del, get, put } from '@/lib/api';
import { errorText } from '@/lib/format';
const RETURN='stocklog://auth';
export default function SocialAdmin(){
 const [data,setData]=useState<any>(null),[forms,setForms]=useState<any>({}),[error,setError]=useState(''),[busy,setBusy]=useState('');
 const load=async()=>{try{setData(await get('/api/admin/social-auth'));setError('')}catch(e){setError(errorText(e))}};useEffect(()=>{void load()},[]);
 const update=(p:string,k:string,v:any)=>setForms((f:any)=>({...f,[p]:{...(f[p]||{}),[k]:v}}));
 const save=async(p:string)=>{setBusy(`save-${p}`);try{const old=data[p]||{},f=forms[p]||{};await put(`/api/admin/social-auth/${p}`,{client_id:f.client_id||'',client_secret:f.client_secret||'',redirect_uri:f.redirect_uri??old.redirect_uri??'',enabled:f.enabled??old.enabled??true});setForms((x:any)=>({...x,[p]:{}}));await load();Alert.alert('저장 완료',`${old.label||p} 로그인 설정을 저장했습니다.`)}catch(e){Alert.alert('저장 실패',errorText(e))}finally{setBusy('')}};
 const test=async(p:string)=>{setBusy(`test-${p}`);try{const start=await get<any>(`/api/admin/social-auth/${p}/test/start`,{return_url:RETURN});const r=await WebBrowser.openAuthSessionAsync(start.authorization_url,RETURN,{showInRecents:true});if(r.type!=='success')return;const u=new URL(r.url);const session=u.searchParams.get('social_test_session');if(!session)throw new Error('OAuth 테스트 세션을 받지 못했습니다.');const result=await get<any>(`/api/admin/social-auth/test-result/${session}`);Alert.alert('OAuth 테스트',result.message||'완료되었습니다.');await load()}catch(e){Alert.alert('테스트 실패',errorText(e))}finally{setBusy('')}};
 const remove=(p:string)=>Alert.alert('소셜 설정 삭제',`${data?.[p]?.label||p} OAuth 설정을 삭제할까요?`,[{text:'취소'},{text:'삭제',style:'destructive',onPress:async()=>{setBusy(`delete-${p}`);try{const r=await del<any>(`/api/admin/social-auth/${p}`);Alert.alert('삭제 완료',r?.message||'삭제했습니다.');await load()}catch(e){Alert.alert('삭제 실패',errorText(e))}finally{setBusy('')}}}]);
 return <Screen><PageHeader eyebrow="ADMIN" title="소셜 로그인" subtitle="Google · Kakao · Naver OAuth 서버 설정과 실제 연결 테스트" right={<Button compact tone="ghost" title="닫기" onPress={()=>router.back()}/>}/>{error?<ErrorState message={error} retry={()=>void load()}/>:!data?<Loading/>:Object.entries(data).map(([p,v]:any)=>{const f=forms[p]||{},enabled=f.enabled??v.enabled??true;return <Card key={p}><SectionTitle title={v.label||p} right={<Chip label={v.configured?'설정됨':'미설정'} active={enabled&&v.configured}/>}/><Text style={s.status}>{v.last_test_message||`테스트: ${v.last_test_status||'미실행'}`}{v.last_tested_at?` · ${new Date(v.last_tested_at).toLocaleString('ko-KR')}`:''}</Text><Text style={s.label}>로그인 사용 여부</Text><View style={s.actions}><Chip label="사용" active={enabled===true} onPress={()=>update(p,'enabled',true)}/><Chip label="비활성" active={enabled===false} onPress={()=>update(p,'enabled',false)}/></View><Field label="Client ID" value={f.client_id||''} onChangeText={x=>update(p,'client_id',x)} placeholder={v.client_id_masked||'비우면 기존 값 유지'}/><Field label="Client Secret" secureTextEntry value={f.client_secret||''} onChangeText={x=>update(p,'client_secret',x)} placeholder={v.has_client_secret?'기존 Secret 유지':'Secret 입력'}/><Field label="Redirect URI" autoCapitalize="none" value={f.redirect_uri??v.redirect_uri??''} onChangeText={x=>update(p,'redirect_uri',x)}/>{p==='google'?<Text style={s.guide}>Google Web application의 redirect URI와 서버 설정을 동일하게 두고 openid/email/profile 범위를 포함해야 합니다.</Text>:null}<View style={s.actions}><Button compact title={busy===`save-${p}`?'저장 중':'저장'} disabled={!!busy} onPress={()=>void save(p)}/><Button compact tone="secondary" title="실제 로그인 테스트" disabled={!!busy||!v.configured} onPress={()=>void test(p)}/>{v.configured?<Button compact tone="danger" title="삭제" disabled={!!busy} onPress={()=>remove(p)}/>:null}</View></Card>})}</Screen>;
}
const s=StyleSheet.create({status:{fontSize:10,color:colors.text3,marginBottom:10,lineHeight:15},label:{fontSize:10,fontWeight:'800',color:colors.text3,marginBottom:4},actions:{flexDirection:'row',gap:8,marginTop:8,flexWrap:'wrap'},guide:{fontSize:10,lineHeight:16,color:colors.text2,backgroundColor:colors.surfaceMuted,padding:9,borderRadius:9,marginTop:8}});
