import { useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Button, Card, Chip, Empty, ErrorState, Field, Loading, PageHeader, Screen, SectionTitle } from '@/components/ui';
import { colors } from '@/constants/theme';
import { del, get, patch } from '@/lib/api';
import { dateTime, errorText } from '@/lib/format';
const tiers=['NORMAL','PREMIUM','EVENT','ADMIN'];
export default function AdminUsers(){const [data,setData]=useState<any>(null),[q,setQ]=useState(''),[page,setPage]=useState(1),[error,setError]=useState(''),[busy,setBusy]=useState(false);const load=async(next=page)=>{try{setData(await get('/api/admin/users',{page:next,page_size:20,q,account_type:'all'}));setError('')}catch(e){setError(errorText(e))}};useEffect(()=>{void load(1)},[]);const tier=async(id:number,value:string)=>{setBusy(true);try{await patch(`/api/admin/users/${id}/membership`,{membership_tier:value});await load()}catch(e){Alert.alert('변경 실패',errorText(e))}finally{setBusy(false)}};const remove=(u:any)=>Alert.alert('회원 삭제',`${u.display_name||u.username} 계정을 삭제할까요?`,[{text:'취소'},{text:'삭제',style:'destructive',onPress:async()=>{try{await del(`/api/admin/users/${u.id}`);await load()}catch(e){Alert.alert('삭제 실패',errorText(e))}}}]);return <Screen><PageHeader eyebrow="ADMIN" title="회원 관리" subtitle="검색, 등급 변경, 계정 삭제" right={<Button compact tone="ghost" title="닫기" onPress={()=>router.back()}/>}/><Card><View style={s.search}><View style={{flex:1}}><Field label="회원 검색" value={q} onChangeText={setQ} placeholder="아이디 또는 이름" returnKeyType="search" onSubmitEditing={()=>{setPage(1);void load(1)}}/></View><Button compact title="검색" onPress={()=>{setPage(1);void load(1)}}/></View>{data?.tier_counts?<View style={s.counts}>{Object.entries(data.tier_counts).map(([k,v])=><Chip key={k} label={`${k} ${v}`}/>)}</View>:null}</Card>{error?<ErrorState message={error} retry={()=>void load()}/>:!data?<Loading/>:data.items?.length?data.items.map((u:any)=><Card key={u.id}><View style={s.head}><View style={{flex:1}}><Text style={s.name}>{u.display_name||u.username}</Text><Text style={s.sub}>{u.username} · 가입 {dateTime(u.created_at)}</Text></View><Chip label={u.membership_tier||u.membership_label||'NORMAL'} active={u.is_admin}/></View><Button compact tone="secondary" title="회원 상세" onPress={()=>router.push(`/admin/user/${u.id}` as any)}/><Text style={s.usage}>AI 오늘 사용 {u.ai_usage?.used||0}{u.ai_usage?.unlimited?'회 · 무제한':` / ${u.ai_usage?.daily_limit??0}회`}</Text><View style={s.tiers}>{tiers.map(t=><Chip key={t} label={t} active={(u.membership_tier||'NORMAL')===t} disabled={busy} onPress={()=>void tier(u.id,t)}/>)}</View>{!u.is_admin?<Button compact tone="danger" title="계정 삭제" onPress={()=>remove(u)}/>:null}</Card>):<Empty title="검색된 회원이 없습니다."/>}{data?.pages>1?<View style={s.pager}><Button compact tone="ghost" title="이전" disabled={page<=1} onPress={()=>{const p=Math.max(1,page-1);setPage(p);void load(p)}}/><Text style={s.page}>{page} / {data.pages}</Text><Button compact tone="ghost" title="다음" disabled={page>=data.pages} onPress={()=>{const p=Math.min(data.pages,page+1);setPage(p);void load(p)}}/></View>:null}</Screen>}
const s=StyleSheet.create({search:{flexDirection:'row',alignItems:'flex-end',gap:8},counts:{flexDirection:'row',gap:6,flexWrap:'wrap',marginTop:12},head:{flexDirection:'row',gap:10,alignItems:'center'},name:{fontSize:15,fontWeight:'800',color:colors.text},sub:{fontSize:10,color:colors.text3,marginTop:4},usage:{fontSize:11,color:colors.text2,marginVertical:10},tiers:{flexDirection:'row',gap:6,flexWrap:'wrap',marginBottom:10},pager:{flexDirection:'row',justifyContent:'center',alignItems:'center',gap:14},page:{fontSize:12,fontWeight:'800',color:colors.text2}})
