import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { AutoAuditDetail } from '@/components/AutoAuditDetail';
import { Button, Card, Chip, Empty, ErrorState, FeatureLocked, Field, Loading, PageHeader, Screen, SectionTitle, Stat } from '@/components/ui';
import { colors } from '@/constants/theme';
import { useAuth } from '@/context/AuthContext';
import { get, post } from '@/lib/api';
import { dateTime, pct, won } from '@/lib/format';

const num=(v:any)=>Number(v||0)||0;
function MiniChart({rows}:{rows:any[]}){
 const values=(rows||[]).slice(-48).map(x=>num(x.close??x.price)).filter(Boolean);
 if(!values.length)return <Text style={styles.muted}>차트 데이터가 없습니다.</Text>;
 const min=Math.min(...values),max=Math.max(...values);
 return <View style={styles.chart}>{values.map((v,i)=><View key={i} style={[styles.chartBar,{height:10+((v-min)/Math.max(1,max-min))*72,backgroundColor:i===values.length-1?colors.primary:'#CDD3E5'}]}/>)}</View>;
}
function TodayFlow({flow}:{flow:any}){
 if(!flow?.available)return <Text style={styles.muted}>오늘 투자자별 매매 데이터를 확인하지 못했습니다.</Text>;
 const primary=[['외국인','foreign'],['기관','institution']],detail=[['금융투자','financial_investment'],['투신','investment_trust'],['연기금 등','pension_etc'],['보험','insurance'],['은행','bank'],['사모펀드','private_equity']];
 const row=([label,key]:string[])=>{const r=flow.categories?.[key]||{},net=num(r.net);return <View key={key} style={styles.flowItem}><Text style={styles.flowLabel}>{label}</Text><Text style={[styles.flowNet,{color:net>=0?colors.positive:colors.negative}]}>{net>=0?'+':''}{won(net)}주</Text><Text style={styles.flowSub}>매수 {won(r.buy)} · 매도 {won(r.sell)}</Text></View>};
 return <View style={{gap:8}}><View style={styles.flowGrid}>{primary.map(row)}</View><View style={styles.flowGrid}>{detail.map(row)}</View><Text style={styles.muted}>기준 {String(flow.date||'').replace(/^(\d{4})(\d{2})(\d{2})$/,'$1-$2-$3')} · 단위 주</Text></View>;
}

export default function Portfolio(){
 const {user}=useAuth();
 const params=useLocalSearchParams<{code?:string;side?:string}>();
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[orderOpen,setOrderOpen]=useState(false),[busy,setBusy]=useState(false);
 const [order,setOrder]=useState({stock_code:'',stock_name:'',side:'buy',quantity:'1',order_type:'market',price:''}),[searchRows,setSearchRows]=useState<any[]>([]);
 const [outlook,setOutlook]=useState<any>(null),[buying,setBuying]=useState<any>(null),[quote,setQuote]=useState<any>(null),[book,setBook]=useState<any>({asks:[],bids:[]}),[orderChart,setOrderChart]=useState<any[]>([]);
 const [audit,setAudit]=useState<any>(null),[refreshSeconds,setRefreshSeconds]=useState(30),[reservations,setReservations]=useState<any[]>([]),[historyTab,setHistoryTab]=useState<'pending'|'filled'|'reservation'>('pending');
 const [holdingInfo,setHoldingInfo]=useState<any>(null),[holdingInfoBusy,setHoldingInfoBusy]=useState(false),[focused,setFocused]=useState(false);
 const canMomentum=user?.features?.portfolio_ai_momentum?.enabled!==false;

 const load=useCallback(async(force=false,silent=false)=>{if(!silent)setLoading(true);if(!silent)setError('');try{
   const [p,b,r,res]=await Promise.allSettled([get<any>('/api/trading/portfolio',{force}),get<any>('/api/trading/buying-power'),get<any>('/api/membership/refresh-policy'),get<any>('/api/trading/reservations')]);
   if(p.status==='fulfilled')setData(p.value);else throw p.reason;
   if(b.status==='fulfilled')setBuying(b.value);
   if(r.status==='fulfilled')setRefreshSeconds(Math.max(0,Number(r.value?.trading_seconds??30)));
   if(res.status==='fulfilled')setReservations(res.value?.items||[]);
   if(canMomentum)get('/api/trading/portfolio/outlook').then(setOutlook).catch(()=>{});else setOutlook(null);
 }catch(e:any){if(!silent)setError(e.message||'포트폴리오를 불러오지 못했습니다.')}finally{if(!silent)setLoading(false)}},[canMomentum]);
 useFocusEffect(useCallback(()=>{setFocused(true);void load(false,false);return()=>setFocused(false)},[load]));
 useEffect(()=>{if(!focused||refreshSeconds<=0)return;const id=setInterval(()=>void load(false,true),Math.max(10,refreshSeconds)*1000);return()=>clearInterval(id)},[focused,refreshSeconds,load]);
 useEffect(()=>{const code=String(params.code||'');if(/^\d{6}$/.test(code)){setOrderOpen(true);setOrder(x=>({...x,stock_code:code,side:params.side==='sell'?'sell':'buy'}));void selectStock({code,name:''})}},[params.code,params.side]);

 const search=async(q:string)=>{setOrder(o=>({...o,stock_code:q,stock_name:''}));if(q.trim().length<1){setSearchRows([]);return}try{const r=await get<any>('/api/stocks/search',{q:q.trim(),limit:8});setSearchRows(Array.isArray(r)?r:(r.items||[]))}catch{setSearchRows([])}};
 const selectStock=async(r:any)=>{const code=String(r.code||'');setOrder(o=>({...o,stock_code:code,stock_name:r.name||o.stock_name}));setSearchRows([]);setOrderChart([]);if(!code)return;const [q,b,c]=await Promise.allSettled([get<any>(`/api/stocks/${code}/quote`),get<any>(`/api/stocks/${code}/orderbook`),get<any>(`/api/stocks/${code}/chart`)]);if(q.status==='fulfilled')setQuote(q.value);if(b.status==='fulfilled')setBook(b.value||{asks:[],bids:[]});if(c.status==='fulfilled')setOrderChart(c.value?.chart||[])};
 const loadHoldingInfo=async(h:any)=>{const code=String(h.code||h.stock_code||'');if(!code)return;if(holdingInfo?.code===code){setHoldingInfo(null);return}setHoldingInfoBusy(true);setHoldingInfo({code,holding:h,chart:[],flow:null});try{const [c,f]=await Promise.allSettled([get<any>(`/api/stocks/${code}/chart/cached`),get<any>(`/api/stocks/${code}/investor-flow`)]);setHoldingInfo({code,holding:h,chart:c.status==='fulfilled'?(c.value?.chart||[]):[],flow:f.status==='fulfilled'?f.value:null})}finally{setHoldingInfoBusy(false)}};
 const submit=async()=>{const code=order.stock_code.trim(),quantity=Number(order.quantity),price=order.order_type==='limit'?Number(order.price||0):null;if(!/^\d{6}$/.test(code)||quantity<=0||(order.order_type==='limit'&&Number(price)<=0)){Alert.alert('주문 확인','종목·수량·지정가를 확인해주세요.');return}Alert.alert('모의주문 확인',`${order.stock_name||code} ${quantity}주 ${order.side==='buy'?'매수':'매도'} 주문을 전송할까요?`,[{text:'취소'},{text:'주문',style:order.side==='sell'?'destructive':'default',onPress:async()=>{setBusy(true);try{const r=await post<any>('/api/trading/order',{side:order.side,stock_code:code,quantity,order_type:order.order_type,price,exchange:'KRX'});Alert.alert('주문 결과',r.message||'주문을 전송했습니다.');await load(true);await selectStock({code,name:order.stock_name})}catch(e:any){Alert.alert('주문 실패',e.message)}finally{setBusy(false)}}}])};

 const summary=data?.summary||{},holdings=data?.holdings||[],orders=data?.orders||[];
 const current=num(quote?.current_price||quote?.price),bestAsk=num(book?.best_ask),bestBid=num(book?.best_bid),estimate=order.order_type==='limit'?num(order.price):current;
 const buyingPower=num(buying?.buying_power??buying?.amount??summary.buying_power??summary.cash),selectedHolding=holdings.find((h:any)=>String(h.code||h.stock_code)===order.stock_code),buyable=estimate>0?Math.floor(buyingPower/estimate):0;
 const pendingOrders=orders.filter((o:any)=>Boolean(o.has_open_order)&&num(o.remaining_qty)>0),filledOrders=orders.filter((o:any)=>!Boolean(o.has_open_order)&&num(o.filled_qty)>0),activeReservations=reservations.filter((r:any)=>r.status==='active');
 const categoryStats=useMemo(()=>{const m=new Map<string,{name:string;value:number;count:number}>();holdings.forEach((h:any)=>{const name=String(h.portfolio_category||h.industry_name||h.sector||h.primary_theme||'기타'),value=num(h.evaluation_amount||h.market_value),x=m.get(name)||{name,value:0,count:0};x.value+=value;x.count+=1;m.set(name,x)});const total=[...m.values()].reduce((a,x)=>a+x.value,0);return [...m.values()].map(x=>({...x,weight:total>0?x.value/total*100:0})).sort((a,b)=>b.value-a.value)},[holdings]);
 const focusedWeight=holdingInfo?.holding&&num(summary.evaluation_amount)?num(holdingInfo.holding.evaluation_amount||holdingInfo.holding.market_value)/num(summary.evaluation_amount)*100:0;
 const historyRows=historyTab==='pending'?pendingOrders:filledOrders;

 return <Screen><AutoAuditDetail row={audit} onClose={()=>setAudit(null)}/><PageHeader eyebrow="MY INVESTMENT" title="포트폴리오" subtitle="보유종목 상세, 실제 일봉·오늘 수급, 호가, 주문과 예약까지 웹 기능을 모바일에 맞게 제공합니다." right={<Button compact tone="ghost" title="새로고침" onPress={()=>void load(true)}/>}/>
 {loading?<Loading label="키움 모의계좌를 확인하고 있습니다."/>:null}{error?<><ErrorState message={error} retry={()=>void load(false)}/><Button title="모의투자 연결 설정" onPress={()=>router.push('/trading/connection')}/></>:null}
 {data?<><Card style={styles.hero}><Text style={styles.heroLabel}>투자 평가액</Text><Text style={styles.heroValue}>{won(summary.evaluation_amount||summary.total_asset)}</Text><Text style={styles.heroSub}>총 자산 {won(summary.total_asset)} · 매입 {won(summary.purchase_amount)} · 계좌 {data.account_no||'-'}</Text><View style={styles.stats}><Stat label="금일 손익" value={won(summary.day_profit)} tone={num(summary.day_profit)>=0?'up':'down'}/><Stat label="총 손익" value={won(summary.profit_loss)} tone={num(summary.profit_loss)>=0?'up':'down'}/><Stat label="수익률" value={pct(summary.return_rate)} tone={num(summary.return_rate)>=0?'up':'down'}/><Stat label="주문가능" value={won(buyingPower)}/></View><View style={styles.heroActions}><Button title="매수 / 매도" onPress={()=>setOrderOpen(v=>!v)}/><Button title="가격감시 예약" tone="secondary" onPress={()=>router.push('/trading/reservations')}/><Button title="연결 설정" tone="ghost" onPress={()=>router.push('/trading/connection')}/></View></Card>
 {orderOpen?<Card style={styles.form}><SectionTitle title="수동 모의주문" hint="종목 선택 시 실제 일봉, 현재가, 5단계 호가와 주문가능수량을 확인합니다."/><View style={styles.chips}><Chip label="매수" active={order.side==='buy'} onPress={()=>setOrder(o=>({...o,side:'buy'}))}/><Chip label="매도" active={order.side==='sell'} onPress={()=>setOrder(o=>({...o,side:'sell'}))}/><Chip label="시장가" active={order.order_type==='market'} onPress={()=>setOrder(o=>({...o,order_type:'market'}))}/><Chip label="지정가" active={order.order_type==='limit'} onPress={()=>setOrder(o=>({...o,order_type:'limit',price:o.price||String(current||'')}))}/></View><Field label="종목코드 / 종목명 검색" value={order.stock_code} onChangeText={v=>void search(v)} placeholder="005930 또는 삼성전자"/>{searchRows.length?<View style={styles.searchBox}>{searchRows.map((r:any)=><Pressable key={r.code} onPress={()=>void selectStock(r)} style={styles.searchRow}><Text style={styles.searchName}>{r.name}</Text><Text style={styles.searchCode}>{r.code} · {r.market||'-'}</Text></Pressable>)}</View>:null}{order.stock_name?<Text style={styles.selected}>{order.stock_name} ({order.stock_code})</Text>:null}
 {current>0?<Card style={styles.quoteCard}><View style={styles.stats}><Stat label="현재가" value={`${won(current)}원`}/><Stat label="최우선 매도" value={bestAsk?`${won(bestAsk)}원`:'-'}/><Stat label="최우선 매수" value={bestBid?`${won(bestBid)}원`:'-'}/><Stat label="매수 가능" value={buyable?`${buyable.toLocaleString()}주`:'-'}/></View><View style={styles.chips}><Chip label={`현재가 ${won(current)}`} onPress={()=>setOrder(o=>({...o,price:String(current)}))}/><Chip label={`매도1 ${bestAsk?won(bestAsk):'-'}`} disabled={!bestAsk} onPress={()=>setOrder(o=>({...o,price:String(bestAsk)}))}/><Chip label={`매수1 ${bestBid?won(bestBid):'-'}`} disabled={!bestBid} onPress={()=>setOrder(o=>({...o,price:String(bestBid)}))}/></View>{(book.asks||[]).length||(book.bids||[]).length?<View style={styles.book}><View style={{flex:1}}><Text style={styles.bookTitle}>매도호가</Text>{(book.asks||[]).slice(0,5).map((x:any,i:number)=><Text key={i} style={styles.bookRow}>{won(x.price||x.ask_price||x[0])} · {num(x.quantity||x.qty||x.ask_qty||x[1]).toLocaleString()}주</Text>)}</View><View style={{flex:1}}><Text style={styles.bookTitle}>매수호가</Text>{(book.bids||[]).slice(0,5).map((x:any,i:number)=><Text key={i} style={styles.bookRow}>{won(x.price||x.bid_price||x[0])} · {num(x.quantity||x.qty||x.bid_qty||x[1]).toLocaleString()}주</Text>)}</View></View>:null}<Text style={styles.bookTitle}>실제 일봉 차트</Text><MiniChart rows={orderChart}/></Card>:null}
 <Field label="수량" value={order.quantity} onChangeText={v=>setOrder(o=>({...o,quantity:v.replace(/\D/g,'')}))} keyboardType="number-pad"/><View style={styles.chips}>{[.25,.5,.75,1].map(r=><Chip key={r} label={`${r*100}%`} onPress={()=>{const base=order.side==='sell'?num(selectedHolding?.quantity):buyable;setOrder(o=>({...o,quantity:String(Math.max(1,Math.floor(base*r))) }))}}/>)}</View>{order.order_type==='limit'?<Field label="지정가" value={order.price} onChangeText={v=>setOrder(o=>({...o,price:v.replace(/[^0-9.]/g,'')}))} keyboardType="numeric"/>:null}<Text style={styles.estimate}>예상 주문금액 {won(Math.max(0,num(order.quantity))*Math.max(0,estimate))}원</Text><Button title={busy?'주문 전송 중...':'주문 전송'} disabled={busy} tone={order.side==='sell'?'danger':'primary'} onPress={()=>void submit()}/></Card>:null}
 <View><SectionTitle title="보유종목" hint={`${holdings.length}종목 · 상세를 열면 저장된 실제 차트와 오늘 수급을 확인합니다.`}/>{!holdings.length?<Empty title="보유종목이 없습니다."/>:holdings.map((h:any)=>{const code=String(h.code||h.stock_code),open=holdingInfo?.code===code;return <Card key={code} style={styles.holding}><View style={styles.holdTop}><View style={{flex:1}}><Text style={styles.name}>{h.name||h.stock_name}</Text><Text style={styles.sub}>{code} · {h.quantity}주 · {h.acquisition_source_label||h.acquisition_source||'직접 매수'}</Text></View><View style={{alignItems:'flex-end'}}><Text style={styles.eval}>{won(h.evaluation_amount||h.market_value)}</Text><Text style={{fontSize:12,fontWeight:'900',color:num(h.return_rate)>=0?colors.positive:colors.negative}}>{pct(h.return_rate)}</Text></View></View><View style={styles.holdStats}><Stat label="평균단가" value={won(h.avg_price)}/><Stat label="현재가" value={won(h.current_price)}/><Stat label="금일손익" value={won(h.day_profit)} tone={num(h.day_profit)>=0?'up':'down'}/><Stat label="총손익" value={won(h.profit_loss)} tone={num(h.profit_loss)>=0?'up':'down'}/></View><View style={styles.chips}><Button compact tone="secondary" title={open?'보유 상세 닫기':'보유 상세'} onPress={()=>void loadHoldingInfo(h)}/><Button compact tone="ghost" title="종목 분석" onPress={()=>router.push(`/stock/${code}` as any)}/>{h.auto_trade_reason?<Button compact tone="secondary" title="AI 체결사유" onPress={()=>setAudit({...h.auto_trade_reason,name:h.auto_trade_reason?.name||h.name,code:h.auto_trade_reason?.code||h.code,portfolio_context:true})}/>:null}</View>{open?<View style={styles.holdingDetail}>{holdingInfoBusy?<Loading label="차트와 오늘 수급을 확인합니다."/>:<><SectionTitle title="가격 차트" hint="저장된 마지막 실제 일봉"/><MiniChart rows={holdingInfo.chart}/><View style={styles.stats}><Stat label="보유수량" value={`${num(h.quantity).toLocaleString()}주`}/><Stat label="매입금액" value={won(h.purchase_amount)}/><Stat label="평가금액" value={won(h.evaluation_amount||h.market_value)}/><Stat label="포트폴리오 비중" value={`${focusedWeight.toFixed(1)}%`}/></View><SectionTitle title="오늘 투자자별 매매"/><TodayFlow flow={holdingInfo.flow}/><View style={styles.chips}><Button compact title="매수 주문" onPress={()=>{setOrderOpen(true);setOrder(x=>({...x,stock_code:code,stock_name:h.name||h.stock_name||'',side:'buy'}));void selectStock({code,name:h.name||h.stock_name})}}/><Button compact tone="danger" title="매도 주문" onPress={()=>{setOrderOpen(true);setOrder(x=>({...x,stock_code:code,stock_name:h.name||h.stock_name||'',side:'sell'}));void selectStock({code,name:h.name||h.stock_name})}}/></View></>}</View>:null}</Card>})}</View>
 {categoryStats.length?<Card><SectionTitle title="테마 · 카테고리 비중" hint="현재 평가액 기준 집중도"/>{categoryStats.slice(0,10).map(x=><View key={x.name} style={styles.mixRow}><View style={{flex:1}}><Text style={styles.name}>{x.name}</Text><Text style={styles.sub}>{x.count}종목 · {won(x.value)}원</Text><View style={styles.track}><View style={[styles.fill,{width:`${Math.min(100,x.weight)}%` as any}]}/></View></View><Text style={styles.mixPct}>{x.weight.toFixed(1)}%</Text></View>)}</Card>:null}
 {canMomentum?(outlook?.enabled?<View><SectionTitle title="보유종목 AI 전망" hint="프리미엄 AI 모멘텀" right={<Button compact tone="ghost" title="분석 실행" onPress={async()=>{try{await post('/api/trading/portfolio/outlook/start',{});Alert.alert('분석 시작','보유종목 AI 분석을 시작했습니다.')}catch(e:any){Alert.alert('실행 실패',e.message)}}}/>} />{(outlook.items||[]).map((x:any)=><Card key={x.code} style={styles.outlook}><Text style={styles.name}>{x.name||x.code}</Text><Text style={styles.outlookText}>{x.analysis?.summary||x.analysis?.outlook||'분석 결과를 준비 중입니다.'}</Text></Card>)}</View>:null):<FeatureLocked title="보유종목 AI 모멘텀" detail="프리미엄 이상 회원은 보유종목의 최근 가격 흐름과 이동평균을 AI가 자동 해석합니다."/>}
 <Card><SectionTitle title="주문 · 예약 관리" hint="웹의 미체결/체결/예약관리 구분과 동일합니다." right={<Button compact tone="ghost" title="새로고침" onPress={()=>void load(true)}/>}/><View style={styles.chips}><Chip label={`미체결 ${pendingOrders.length}`} active={historyTab==='pending'} onPress={()=>setHistoryTab('pending')}/><Chip label={`체결 ${filledOrders.length}`} active={historyTab==='filled'} onPress={()=>setHistoryTab('filled')}/><Chip label={`예약 ${activeReservations.length}`} active={historyTab==='reservation'} onPress={()=>setHistoryTab('reservation')}/></View>{historyTab==='reservation'?(!reservations.length?<Empty title="예약 주문이 없습니다."/>:<View style={{gap:7}}>{reservations.slice(0,30).map((r:any)=><View key={r.id} style={styles.historyRow}><View style={{flex:1}}><Text style={styles.name}>{r.stock_name||r.stock_code}</Text><Text style={styles.sub}>{r.side_label||r.side} · {won(r.trigger_price)}원 {r.trigger_operator==='lte'?'이하':'이상'} · {r.quantity}주 · {r.status_label||r.status}</Text></View>{r.status==='active'?<Button compact tone="ghost" title="관리" onPress={()=>router.push('/trading/reservations')}/>:null}</View>)}</View>):(!historyRows.length?<Empty title={historyTab==='pending'?'현재 미체결 주문이 없습니다.':'실제 체결 완료된 주문 내역이 없습니다.'}/>:<View style={{gap:7}}>{historyRows.slice(0,30).map((o:any,i:number)=><View key={`${o.order_no||i}`} style={styles.historyRow}><View style={[styles.side,{backgroundColor:String(o.side).includes('sell')||String(o.side).includes('매도')?colors.negativeSoft:colors.positiveSoft}]}><Text style={{fontSize:9,fontWeight:'900',color:String(o.side).includes('sell')||String(o.side).includes('매도')?colors.negative:colors.positive}}>{o.side_label||o.side||'-'}</Text></View><View style={{flex:1}}><Text style={styles.name}>{o.name||o.stock_name||o.code}</Text><Text style={styles.sub}>{o.code||o.stock_code} · 주문 {num(o.order_qty||o.quantity).toLocaleString()}주 · 체결 {num(o.filled_qty).toLocaleString()}주{historyTab==='pending'?` · 미체결 ${num(o.remaining_qty).toLocaleString()}주`:''} · {dateTime(o.time||o.created_at)}</Text></View><Text style={styles.orderPrice}>{num(o.price)>0?`${won(o.price)}원`:'시장가'}</Text></View>)}</View>)}</Card>
 </>:null}</Screen>;
}

const styles=StyleSheet.create({
 hero:{backgroundColor:colors.navy,borderColor:colors.navy},heroLabel:{fontSize:10,fontWeight:'800',color:'#9EA9BA'},heroValue:{fontSize:29,fontWeight:'900',color:'#fff',marginTop:5},heroSub:{fontSize:10,color:'#B7C1D0',marginTop:5},stats:{flexDirection:'row',flexWrap:'wrap',gap:12,marginVertical:12},heroActions:{gap:8},form:{gap:11},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},
 searchBox:{borderWidth:1,borderColor:colors.border,borderRadius:12,overflow:'hidden'},searchRow:{flexDirection:'row',justifyContent:'space-between',padding:11,borderBottomWidth:1,borderBottomColor:colors.border},searchName:{fontSize:12,fontWeight:'800',color:colors.text},searchCode:{fontSize:11,color:colors.text3},selected:{fontSize:11,fontWeight:'800',color:colors.primary},quoteCard:{shadowOpacity:0,backgroundColor:colors.surfaceMuted},book:{flexDirection:'row',gap:16},bookTitle:{fontSize:11,fontWeight:'900',color:colors.text2,marginBottom:5,marginTop:6},bookRow:{fontSize:10,color:colors.text3,lineHeight:17},estimate:{fontSize:11,fontWeight:'700',color:colors.text2},
 chart:{height:90,flexDirection:'row',alignItems:'flex-end',gap:2,paddingTop:6},chartBar:{flex:1,minWidth:2,borderRadius:2},muted:{fontSize:10,color:colors.text3,lineHeight:16},holding:{gap:12,padding:13,marginBottom:7,shadowOpacity:0},holdTop:{flexDirection:'row',alignItems:'center',gap:8},name:{fontSize:14,fontWeight:'800',color:colors.text},sub:{fontSize:10,color:colors.text3,marginTop:4,lineHeight:15},eval:{fontSize:14,fontWeight:'800',color:colors.text},holdStats:{flexDirection:'row',flexWrap:'wrap',gap:8},holdingDetail:{gap:10,paddingTop:10,borderTopWidth:1,borderTopColor:colors.border},
 flowGrid:{flexDirection:'row',flexWrap:'wrap',gap:7},flowItem:{width:'48.5%',padding:9,borderRadius:10,backgroundColor:colors.surfaceMuted},flowLabel:{fontSize:9,fontWeight:'800',color:colors.text3},flowNet:{fontSize:12,fontWeight:'900',marginTop:3},flowSub:{fontSize:8,color:colors.text3,marginTop:3},mixRow:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:9,borderBottomWidth:1,borderBottomColor:colors.border},mixPct:{fontSize:12,fontWeight:'900',color:colors.text2},track:{height:5,borderRadius:999,backgroundColor:colors.surfaceMuted,marginTop:6,overflow:'hidden'},fill:{height:5,borderRadius:999,backgroundColor:colors.primary},
 outlook:{marginBottom:7,shadowOpacity:0},outlookText:{fontSize:11,color:colors.text2,lineHeight:17,marginTop:6},historyRow:{flexDirection:'row',alignItems:'center',gap:9,paddingVertical:9,borderBottomWidth:1,borderBottomColor:colors.border},side:{width:42,height:30,borderRadius:9,alignItems:'center',justifyContent:'center'},orderPrice:{fontSize:10,fontWeight:'800',color:colors.text2}
});
