import { useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Button, Card, ErrorState, Field, Loading, PageHeader, Screen, SectionTitle, Stat } from '@/components/ui';
import { colors } from '@/constants/theme';
import { get, post, put } from '@/lib/api';
import { dateTime, errorText } from '@/lib/format';
export default function TradingConnection(){const [data,setData]=useState<any>(null),[appKey,setAppKey]=useState(''),[secret,setSecret]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const load=async()=>{try{setData(await get('/api/trading/connection'));setError('')}catch(e){setError(errorText(e))}};useEffect(()=>{void load()},[]);const save=async()=>{setBusy(true);try{const r=await put('/api/trading/connection',{app_key:appKey,secret_key:secret,account_no:'',use_mock:true});setData(r?.settings||data);setAppKey('');setSecret('');Alert.alert('연결 완료',r?.message||'키움 모의투자 계좌를 연결했습니다.');await load()}catch(e){Alert.alert('저장 실패',errorText(e))}finally{setBusy(false)}};const test=async()=>{setBusy(true);try{const r=await post('/api/trading/connection/test',{});Alert.alert('연결 확인',r?.message||'키움 연결이 정상입니다.');await load()}catch(e){Alert.alert('연결 실패',errorText(e))}finally{setBusy(false)}};return <Screen><PageHeader eyebrow="KIWOOM" title="모의투자 연결" subtitle="앱에는 키를 저장하지 않고 StockLog 서버가 암호화해 보관합니다." right={<Button compact tone="ghost" title="닫기" onPress={()=>router.back()}/>}/>{error?<ErrorState message={error} retry={()=>void load()}/>:!data?<Loading/>:<><Card><SectionTitle title="현재 연결"/><View style={s.stats}><Stat label="상태" value={data.connected?'연결됨':'미연결'}/><Stat label="계좌" value={data.account_no||'-'}/></View><Text style={s.note}>최근 연결: {dateTime(data.last_connected_at)}</Text><Button compact tone="secondary" title="연결 테스트" disabled={busy||!data.has_app_key||!data.has_secret_key} onPress={test}/></Card><Card><SectionTitle title="App Key / Secret Key" hint="빈 칸으로 저장하면 기존 키를 유지합니다."/><View style={s.form}><Field label="App Key" autoCapitalize="none" value={appKey} onChangeText={setAppKey} placeholder={data.has_app_key?'기존 App Key 유지':'App Key 입력'}/><Field label="Secret Key" autoCapitalize="none" secureTextEntry value={secret} onChangeText={setSecret} placeholder={data.has_secret_key?'기존 Secret Key 유지':'Secret Key 입력'}/><Text style={s.warn}>StockLog UI에서는 안전을 위해 키움 모의투자 계정만 연결합니다.</Text><Button title="저장하고 계좌 자동 찾기" disabled={busy||(!appKey&&!data.has_app_key)||(!secret&&!data.has_secret_key)} onPress={save}/></View></Card></>}</Screen>}
const s=StyleSheet.create({stats:{flexDirection:'row',gap:14},form:{gap:12},note:{fontSize:11,color:colors.text3,marginVertical:10},warn:{fontSize:11,lineHeight:17,color:colors.warning}})
